import React from 'react';

const texts = {
  details: "Detaily",
  close: "Zavrieť",
  products: "Produkty",
  contact: "Kontakt",
  howToOrder: "Ako Objednať",
  downloads: "Na Stiahnutie",
  jobs: "Ponuka práce",
  search: "Hľadať",
  companyName: "Bflex, s.r.o.",
  companySlogan: "Predaj a technické poradenstvo",
  create: "Vytvoriť",
  cancel: "Zrušiť",
  delete: "✖",
  productNamePlaceholder: "Názov produktu",
  productDescriptionPlaceholder: "Popis produktu",
  productTagsPlaceholder: "Tagy",
  chooseCategoryPlaceholder: "Vybrať kategóriu",
  tableColumnsPlaceholder: "Stĺpce tabulky (oddelovať s ;)",
  tableRowsPlaceholder: "Riadky tabulky (oddelovať s ;)",
  login: "Prihlásiť sa",
  namePlaceholder: "Login",
  passwordPlaceholder: "Heslo",
  emailPlaceholder: "Email",
  categoryNamePlaceholder: "Názov kategórie",
  categoryDescriptionPlaceholder: "Popis kategórie",
  newestProducts: "Najnovšie produkty",
  howToOrderDescription: "Na karte produktu sa nachádza tlačidlo Pridať. Po jeho stlačení sa otvorí zoznam vybratého tovaru, do ktorého môžete ďalej pridávať. Keď budete mať všetko vybraté, stlačte tlačidlo Odoslať záujem. Následne vyplňte vaše meno, email a prípadnú poznámku. Bude vám zaslaná potvrdenka a s ďalším postupom Vás budeme následne kontaktovať.",
  searchResultFor: "Výsledok hľadania: ",
  send: "Odoslať",
  sent: "Váš záujem bol odoslaný, v najbližších dňoch Vás budeme kontaktovať.",
  orderInterest: "Odoslať záujem",
  addToCart: "Pridať",
  yourContact: "Kontakt na Vás",
  yourName: "Vaše meno:",
  yourEmail: "Váš Email:",
  note: "Poznámka:",
  noJobsOpenATM: "Momentálne nemáme otvorené žiadne pracovné pozície",
  jobNamePlaceholder: "Názov Pozície",
  jobDescriptionPlaceholder: "Popis pozície",
  downloadLink: "Stiahnuť",
  fileNamePlaceholder: "Názov súboru",
  fileDescriptionPlaceholder: "Popis súboru",
  orderUP: "▲",
  orderDown: "▼",
  dataNotCollected: "Váše meno ani email nebudú nikde uložené.",
};

const constants = {
  endpoint: 'https://bflex-api.herokuapp.com',
};

export{texts, constants}